class _BotCommands:
    def __init__(self):
        self.StartCommand = 'stt'
        self.MirrorCommand = 'mir1'
        self.UnzipMirrorCommand = 'unzip1'
        self.TarMirrorCommand = 'tar1'
        self.CancelMirror = 'can1'
        self.CancelAllCommand = 'cnlall1'
        self.ListCommand = 'list1'
        self.StatusCommand = 'sttus1'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauth1'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stat1'
        self.HelpCommand = 'hlp'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'speedtest1'
        self.CloneCommand = 'clone1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage1'
        self.RepoCommand = 'supportus'

BotCommands = _BotCommands()
